---
- name: restart service on CentOS
  ansible.builtin.service:
    name: chronyd
    state: restarted
  when: ansible_distribution == "CentOS"

- name: restart service on Ubuntu
  ansible.builtin.service:
    name: ntp
    state: restarted
  when: ansible_distribution == "Ubuntu"