---
# tasks file for post-install
- name: Install NTP agent on CentOS
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - wget
    - git
    - zip
    - unzip

- name: Install NTP agent on Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Start service on CentOS
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Start service on Ubuntu
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  ansible.builtin.copy:
    content: "# This server is managed by ansible. NO MANYAL CHANGES PLEASE!"
    dest: /etc/motd

- name: Create a folder
  ansible.builtin.file:
    path: "{{ mydir }}"
    state: directory

- name: Deploy ntp agent conf on CentOS
  ansible.builtin.template:
    src: ntpconf_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify: restart service on CentOS

- name: Deploy ntp agent conf on Ubuntu
  ansible.builtin.template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntpsec/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify: restart service on Ubuntu

- name: Dump a file
  ansible.builtin.copy:
    src: myfile.txt
    dest: /tmp/myfile.txt
