---
# defaults file for post-install
USRNM: globaluser
COMM: value from group_vars/all file
ntp0: 0.north-america.pool.ntp.org
ntp1: 1.north-america.pool.ntp.org
ntp2: 2.north-america.pool.ntp.org
ntp3: 3.north-america.pool.ntp.org
mydir: /opt/dir22