---
- name: DBserver setup
  hosts: dbservers
  become: yes

  vars:
    dbname: electric
    dbuser: current
    dbpass: tesla

  tasks:
    - name: Print db name
      ansible.builtin.debug:
        msg: "The db name is: {{ dbname }}"

    - name: Print db user
      ansible.builtin.debug:
        var: dbuser

    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start mariadb-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      community.mysql.mysql_db:
        name: "{{ dbname }}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user
      community.mysql.mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpass }}"
        priv: "*.*:ALL"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbout

    - name: print dbout variable
      debug:
        var: dbout        