---
- name: DBserver setup
  hosts: dbservers
  become: yes
  vars:
    dbname: electric
    dbuser: current
    dbpass: teska
  tasks:
   - name: Install mariadb-server
     ansible.builtin.yum:
      name: mariadb-server
      state: present
  
   - name: Install pymysql
     ansible.builtin.yum:
      name: python3-PyMySQL
      state: present

   - name: Start mariadb-server
     ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes

   - name: Create a new database
     community.mysql.mysql_db:
      name: "{{dbname}}"
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock

   - name: Create database
     community.mysql.mysql_user:
      name: "{{dbuser}}"
      password: "{{dbpass}}"
      priv: '*.*:ALL'
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
