---
- name: Provisioning servers
  hosts: all
  become: yes
  vars:
    dir1: /opt/dir22
  tasks:
    - name: Install NTP agent on CentOS
      yum:
        name: "{{ item }}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP agent on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start service on CentOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"          

    - name: Banner file
      ansible.builtin.copy:
        content: '# This server is managed by ansible. NO MANYAL CHANGES PLEASE!'
        dest: /etc/motd

    - name: Create a folder
      ansible.builtin.file:
        path: "{{ mydir }}"
        state: directory    

    - name: Deploy ntp agent cont on CentOS
      ansible.builtin.template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
      notify: reStart service on CentOS

    - name: Deploy ntp agent cont on Ubuntu
      ansible.builtin.template:
        src: templates/ntpconf_ubuntu
        dest: /etc/ntpsec/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
      notify: reStart service on Ubuntu

    - name: Dump a file
      copy:
        files: files/myfile.txt
        dest: /tmp/myfile.txt
  
  handlers:
    - name: reStart service on CentOS
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: reStart service on Ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    
